package com.myspace.demo202207_bapl_1963;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.Integer age;
	private java.lang.Boolean allowed;
	
	public String toString() {
	    return "Person("+ name+", "+age+", "+allowed+")";
	}

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getAllowed() {
		return this.allowed;
	}

	public void setAllowed(java.lang.Boolean allowed) {
		this.allowed = allowed;
	}

	public Person(java.lang.String name, java.lang.Integer age,
			java.lang.Boolean allowed) {
		this.name = name;
		this.age = age;
		this.allowed = allowed;
	}

}