package com.myspace.demo202207_bapl_1963;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Person() {
    }




}